config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :uploads

  root to: "uploads#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/upload.rb
class Upload < ApplicationRecord
  mount_uploader :file, FileUploader
  process_in_background :file

  validates_presence_of :file
  belongs_to :user

  def name
    file.path.split("/").last unless file.nil?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :uploads
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  before_action :set_upload, only: [:show, :edit, :update, :destroy]

  # GET /uploads
  # GET /uploads.json
  def index
    @uploads = Upload.all
  end

  # GET /uploads/1
  # GET /uploads/1.json
  def show
  end

  # GET /uploads/new
  def new
    @upload = Upload.new
  end

  # GET /uploads/1/edit
  def edit
  end

  # POST /uploads
  # POST /uploads.json
  def create
    upload_params[:files].each do |file|
      @upload = Upload.new({"file" => file })
      # if @upload.save
      #   notice << "#{@upload.name} uploaded successfully"
      # else
      #   errors << "#{@upload.name} upload unsuccessful"
      # end
    end
    # byebug
    respond_to do |format|
      format.html { redirect_to Upload.last, notice: "uploaded successfully" }
      format.json { render :show, status: :created, location: @upload }
    end
  end

  # PATCH/PUT /uploads/1
  # PATCH/PUT /uploads/1.json
  def update
    respond_to do |format|
      if @upload.update(upload_params)
        format.html { redirect_to @upload, notice: 'Upload was successfully updated.' }
        format.json { render :show, status: :ok, location: @upload }
      else
        format.html { render :edit }
        format.json { render json: @upload.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /uploads/1
  # DELETE /uploads/1.json
  def destroy
    @upload.destroy
    respond_to do |format|
      format.html { redirect_to uploads_url, notice: 'Upload was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_upload
      @upload = Upload.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def upload_params
      params.require(:upload).permit(:files => [])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">UploadThem</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <a class="nav-link" href="/uploads">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/uploads/new">Upload</a>
        </li>
      <% end %>
    </ul>
    <span class="navbar-text">
      <% if user_signed_in? %>
        Logged in as <strong><%= current_user.email %></strong>.
        <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
        <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
      <% else %>
        <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
              <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
      <% end %>
    </span>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UploadThem</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="container">
    <%= render "layouts/navbar" %>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/uploads/_form.html.erb
<%= bootstrap_form_with(model: upload, local: true) do |form| %>
  <% if upload.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(upload.errors.count, "error") %> prohibited this upload from being saved:</h2>

      <ul>
      <% upload.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="progress">
    <div class="progress-bar progress-bar-striped bg-success" role="progressbar" style="width: 0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"></div>
  </div>

  <div class="field form-group col-md-4">
    <%= form.file_field :files, multiple: true, class: "custom-file-input" %>
    <p id="upload-file-info">Chosen file(s): none</p>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>

<% end %>

<script>


</script>

app/views/uploads/edit.html.erb
<h1>Editing Upload</h1>

<%= render 'form', upload: @upload %>

<%= link_to 'Show', @upload %> |
<%= link_to 'Back', uploads_path %>

app/views/uploads/index.html.erb
<h1>Uploads</h1>

<table class="table table-striped">
  <thead class="thead thead-light">
  <tr>
    <th>Name</th>
    <th colspan="4">Options</th>
  </tr>
  </thead>

  <tbody>
  <% @uploads.each do |upload| %>
    <tr>
      <td><%= upload.name %></td>
      <td><%= link_to 'Show', upload %></td>
      <td><%= link_to 'Edit', edit_upload_path(upload) %></td>
      <td><%= link_to "Download", upload.file_url %></td>
      <td><%= link_to 'Destroy', upload, method: :delete, data: { confirm: 'Are you sure?' } %></td>

    </tr>
  <% end %>
  </tbody>
</table>

<br>


<%= link_to 'New Upload', new_upload_path %>

app/views/uploads/new.html.erb
<h1>New Upload</h1>

<%= render 'form', upload: @upload %>

<%= link_to 'Back', uploads_path %>

app/views/uploads/show.html.erb
<br>
<div class="row">
  <p class="col-md-8"><b>Name: </b><%= @upload.name %></p>
  <p class="col-md-3"><b>Size: </b><%= @upload.file_size %></p>
</div>
<div >
  <%= link_to "Download File", @upload.file_url %> |
  <%= link_to 'Edit', edit_upload_path(@upload) %> |
  <%= link_to 'Destroy', @upload, data: { confirm: 'Are you sure?' }, method: :delete %> |
  <%= link_to 'Back', uploads_path %>
</div>